#!/usr/bin/env bash

# This trap catches the SIGTERM signal.
# Instead of stopping the script,
# it prints "I am invincible!!!"
trap 'echo "I am invincible!!!"' SIGTERM

# Infinite loop
while true
do
    # Display message
    echo "To infinity and beyond"

    # Wait 2 seconds before repeating
    sleep 2
done
